### ISSUE TITLE
to_fix

### ISSUE THREAD

**Issue by tenhishadow** [palchyk-alex/lab02-ansible#1]
https://github.com/palchyk-alex/lab02-ansible/blob/26521167550c2933ac851a5412b71f0770c81a93/ansible.cfg#L10

нет смысла это указывать в ansible.cfg
лучше в плейбуке тупо написать become: yes

https://github.com/palchyk-alex/lab02-ansible/blob/main/inventory
переделай его на yaml для практики.
например вот так: https://github.com/tenhishadow/dotfiles/tree/master/inventory

ansible_user=ec2-user надо вынести в group_vars( потому что она общая, не так ли? )

ansible_host=107.23.251.186 
что это такое? Нельзя ли использовать aws plugin?
всего-то надо:
```
# ansible.cfg
[defaults]
...
enable_plugins       = aws_ec2
```
https://docs.ansible.com/ansible/latest/plugins/inventory.html

и дальше уже параметры поиска по тегам и прочему:

```yaml
# ./inventory/aws_ec2.yml
--- # common inventory for all labs

plugin: aws_ec2

aws_profile: itechart

regions:
  - 'eu-central-1'

filters:
  tag:Project:
    - DevOpsLab
#   tag:Stage:
#     - RHCSA
  instance-state-name : running

keyed_groups:
  - key: tags.Lab
    separator: ''

...
```

и весь конфиг:
```
# ansible.cfg

[defaults]
command_warnings     = True
deprecation_warnings = True
enable_plugins       = aws_ec2
inventory            = ../../common/ansible/inventory/
remote_user          = ec2-user
retry_files_enabled  = False
stdout_callback      = yaml
system_warnings      = True
timeout              = 120

[ssh_connection]
retries = 30
```

https://github.com/palchyk-alex/lab02-ansible/tree/main/roles/setup_storage_servers/files

никаких files( по крайней мере сейчас )
всё нужно переделать в template( более универсально )
конкретно тут:
https://github.com/palchyk-alex/lab02-ansible/blob/26521167550c2933ac851a5412b71f0770c81a93/roles/setup_web_servers/files/index.html#L5

```vm-01```
достать из фактов(gather_facts включи)

https://github.com/palchyk-alex/lab02-ansible/blob/26521167550c2933ac851a5412b71f0770c81a93/roles/setup_web_servers/files/nginx-stable.repo#L3

```
http://nginx.org/packages/centos/7/x86_64/
```
centos - из фактов.
7 - из фактов
разрядность тоже из фактов :)

https://github.com/palchyk-alex/lab02-ansible/blob/main/roles/setup_web_servers/files/nginx-stable.repo
сначала переделай через template и всё сделай через факты.

+ есть модуль получше
https://docs.ansible.com/ansible/2.9/modules/yum_repository_module.html

где pipenv?

Почитай про него тут:
https://webdevblog.ru/pipenv-rukovodstvo-po-novomu-instrumentu-python/
https://habr.com/ru/post/413009/

и зафикси версию и скрипты как тут:
https://github.com/tenhishadow/dotfiles/blob/master/Pipfile
